language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: x25AKiGbs5UMbycwjH/g896fBsM6obDnmfcsSLUoy3v93LYgHJ4Uv44H5d69dJfq/4VZkOltZTwtikiuR6y0cKIjclviBYGW68n1JWE44j2MNonLGlyMx6g7p24G21kvY81CEJJUVC3BwaBu/2S1hqvfY9sgouq/o/jHhqu2YRpyYKUUuIkO5WYAJFrG4RcxUPU7VJGn7Vb7XQG/f6NO58Ge9J4zmZjFJx+G1tGpvaO/BJI6Ts72EsLC8+bB0nRgXFhSqJS/hDnHlNxMffwJTpyQ/iWFbzbhEclH1vUk3/u1YaU8yEABF8lA+I1wBRQvYsLUHLGPS+E3CjjAmxuHNJhS5bljfyJzgn+TieVqeRjKdbPNBi8v7G+seC2GN7hM4dmpHtJzqINran+/zgkx9InrFMZPDWyC7qPWWFpyVN0yoJCXGeh5nmFvdSIidgKd4p8zScP7TdCvWnZWman1V9kiLrR1pUZMwaQROpKKw3BD3Sv0N9C+gDNtVNYIc3ZP5UEh2DDDl7tFTScTKIprryYQi7pkBnQHUYZ9rjztynn6pcurunHnc4QZ2DWA9RGcqIvS+TIM5+Ayx+C84dz/j3kICBLaMuDoKSuiz/ZHcGIf149kqMvZ1JWlMtuxmPQioGgIxOUgqwTKqRLj5/o86UMjArkHcrF3NGyYOlKTSq0=
  app: shielded-woodland-72080
  on:
    repo: Edisonsim/Express-edison
